wri/gfw_forest_loss_geotrellis

src/main/scala/org/globalforestwatch/treecoverloss/TenByTenGridSources.scala
src/main/scala/org/globalforestwatch/treecoverloss/TreeLossRDD.scala
src/main/scala/org/globalforestwatch/treecoverloss/TreeLossSummary.scala
src/main/scala/org/globalforestwatch/treecoverloss/TreeLossTile.scala

- TreeLossSummary tile has some optional tiles
- co2Pixel and gadm36 are optional rasters

Optional Raster Support

---

src/main/scala/org/globalforestwatch/treecoverloss/TenByTenGrid.scala
src/main/scala/org/globalforestwatch/treecoverloss/TenByTenGridSources.scala

- Check if files exist for optional raster sources
- Don't check for intersection for files that we don't require for analysis

Optional Sources

---

src/main/scala/org/globalforestwatch/treecoverloss/TenByTenGridSources.scala

Gives informative error message when its missing a file we expected to be there.

Add TenByTenGridSouce.requiredSource

---

build.sbt
src/main/scala/org/globalforestwatch/gladalerts/GladAlertsRDD.scala
src/main/scala/org/globalforestwatch/treecoverloss/TreeLossRDD.scala
src/main/scala/org/globalforestwatch/util/GeoJsonUtil.scala
src/main/scala/org/globalforestwatch/util/Implicits.scala

Fix GeoTrellis 3 Imports

---

src/main/scala/org/globalforestwatch/annualupdate_minimal/TreeLossSummaryMain.scala
version.sbt

Signed-off-by: Thomas Maschler <tmaschler@wri.org>

add summary stats back into annual update minimal

---

build.sbt
src/main/scala/org/globalforestwatch/features/GeostoreFeature.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDFFactory.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalRow.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalRowGadm.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalRowGeostore.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/dataframes/GeostoreDF.scala
src/main/scala/org/globalforestwatch/summarystats/gladalerts/GladAlertsDFFactory.scala
src/main/scala/org/globalforestwatch/summarystats/gladalerts/GladAlertsRowGeostore.scala

A few fixes to get geostore feature type working

---

src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDF.scala
version.sbt

Signed-off-by: Thomas Maschler <tmaschler@wri.org>
Issue Number: regional primary forest layer was missing in export files for annual update minimum
- added regional primary forest back into export tables for annual update minimum
-
-

add regional primary forest back into annual update minimum

---

src/main/scala/org/globalforestwatch/layers/KeyBiodiversityAreas.scala
src/main/scala/org/globalforestwatch/layers/Layer.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDownloadDF.scala

For new data lake, doesObjectExist will give error for credentials without ListBucket access, so catch exception and behave same for required/optional layers. Fix KBA layer version. Fix download export to keep ISOs without adm2 boundaries, and turn nulls to 0s in missed places.
Issue Number: N/A
-
-
-

Production issues

---

src/main/scala/org/globalforestwatch/layers/Aze.scala
src/main/scala/org/globalforestwatch/layers/IndonesiaForestArea.scala
src/main/scala/org/globalforestwatch/layers/KeyBiodiversityAreas.scala
src/main/scala/org/globalforestwatch/layers/ProtectedAreas.scala
src/main/scala/org/globalforestwatch/layers/TreeCoverLossDrivers.scala
src/main/scala/org/globalforestwatch/layers/WoodFiber.scala

Signed-off-by: Thomas Maschler <tmaschler@wri.org>
Fix version number and names. This new source files are identical to old source files. (IDN forest area was completely wrong and pointed to non existing version)
- [GTC-440]
- [GTC-441]
- [GTC-629]
[GTC-440]: https://gfw.atlassian.net/browse/GTC-440

fix version number

---

README.md
src/main/scala/org/globalforestwatch/layers/Plantations.scala
src/main/scala/org/globalforestwatch/summarystats/SummaryMain.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossDF.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossDataGroup.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossExport.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossGridSources.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossSummary.scala
src/main/scala/org/globalforestwatch/summarystats/treecoverloss/TreeLossTile.scala
version.sbt

Signed-off-by: Thomas Maschler <tmaschler@wri.org>
Issue Number: 
- [GTC-641]
- Add option to include gfw_plantations to tree cover loss analysis
Instead of using `primary_forest` flag, users now need to specify full name of contextual layers they want to include.
supported layers are `is__umd_regional_primary_forest_2001` and `gfw_plantations`. All other values will be ignored.
[GTC-641]: https://gfw.atlassian.net/browse/GTC-641

add option to include plantations layer to tree cover loss analysis

---

src/main/scala/org/globalforestwatch/layers/GrossEmissionsCo2OnlyCo2e.scala
src/main/scala/org/globalforestwatch/layers/GrossEmissionsNodeCodes.scala
src/main/scala/org/globalforestwatch/layers/GrossEmissionsNonCo2Co2e.scala
src/main/scala/org/globalforestwatch/layers/NetFluxCo2e.scala
src/main/scala/org/globalforestwatch/layers/TreeCoverLossDrivers.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDownloadDF.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalExport.scala
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalSummary.scala
version.sbt

- Update download DF with new carbon layers
- Remove is__gain column from TCL tables and instead just calculate the emissions correctly in the summary
- Point back to the 2019 flux layers since 2020 layers had some issues
-

Update download DF

---

src/main/scala/org/globalforestwatch/layers/IndonesiaLandCover.scala
src/main/scala/org/globalforestwatch/summarystats/SummaryCommand.scala
src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
src/main/scala/org/globalforestwatch/util/FeatureFlag.scala
version.sbt

- [ x Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
Currently the landcover labels for Pro do not match labels used for Flagship, using a smaller set which groups landcover types together. This PR introduces a feature flag for GFW pro provided at command line as `--gfwpro` that switches this behavior.
`\
The default value for the flag is false, so current behavior will not change

GfwPro feature flag for IDN landcover labels

---

src/main/scala/org/globalforestwatch/layers/GladAlerts.scala
src/main/scala/org/globalforestwatch/layers/Layer.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardCommand.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardData.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardDataDateCount.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardRawData.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardRawDataGroup.scala
src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardSummary.scala

Weird aggregations into weekly and monthly results
More reasonable aggregations of glad alerts into weekly/monthly buckets.
Noted that MODIS/VIIRS alerts are not counted properly right now.

Fix dashboard glad alert aggregations

---

src/main/scala/org/globalforestwatch/summarystats/SummaryMain.scala

Bad arguments result in process terminating with exit code 0.
This hides the error when executed from batch.
Exit with code 2

Exit code 2 on bad args

---

src/main/resources/raster-catalog-default.json
src/main/resources/raster-catalog-pro.json

Issue Number: GTC-2052
- Adding Q4 WDPA contextual layer update
- Adding GFW Oil and Gas concessions contextual layer update
- Adding Burned areas update

Add Q4 contextual layer update

---

README.md
src/main/scala/org/globalforestwatch/summarystats/integrated_alerts/IntegratedAlertsCommand.scala

Also updated with the fact that the subcommand (the analysis) is now always provided as the first argument (and without the --analysis option)
Fixed a help message for the integrated alerts subcommand.

Update README.md with new subcommands (analyses) and cmd-line options

---

src/main/scala/org/globalforestwatch/summarystats/afi/AFiSummary.scala

Aggregates pixels where negligible risk == NO 
Issue Number: [GTC-2590](https://gfw.atlassian.net/browse/GTC-2590)
- Aggregates pixels where negligible risk == YES
-
[GTC-2590]: https://gfw.atlassian.net/browse/GTC-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GTC-2590 Address AFi QC bugs

---

src/main/resources/raster-catalog-default.json
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDownloadDF.scala

Issue Number: https://gfw.atlassian.net/browse/GTC-2755
Update  TCL to 2023.

Update TCL to 2023 in annual update

---

src/main/scala/org/globalforestwatch/config/RasterCatalog.scala

GTC-2823 Fix retries when getting latest version of a dataset
I noticed that the retry code in RasterCatalog.getLatestVersion was not correct. It was using recursion to do one or more retries, but wasn't actually using any successful response from a retry, but instead still used the original unsuccessful response. Broke out a separate function getLatestVersionResponse() to fix the problem. I am still doing 2 more retries after the first request.
Also, increased the connection timeout from 10 seconds to 20 seconds.
These fixes should make Geotrellis more resilient to slow responses from the Data API. With a bigger change, I could also get rid of the "latest version" requests for FCD and AFI analyses, since they don't actually use the integrated alerts dataset.

GTC-2823 Fix retries when getting latest version of a dataset

---

src/main/scala/org/globalforestwatch/summarystats/ErrorSummaryRDD.scala

Reuse analysis results for same full-window geometries from different locations
This is an optimization that Justin did a while ago for GFW in SummaryRDD.scala. I'm porting it to ErrorSummaryRDD.scala, which is what GFWPro uses.
If several locations overlap an entire window, then only do the analysis on that window once, and use it as one of the partial results for all those locations. This optimization is especially useful when locations have a lot of overlap, possibly because there are lots of large, overlapping, supply sheds, or because of the batching of lots of related lists in the ALERTS-Batch analysis.
I believe that the extra check to see if a geometry completely covers a window should be inexpensive when it doesn't apply, so this optimization shouldn't noticeably increase the …

Reuse analysis results for same full-window geometries from different locations

---

src/main/resources/raster-catalog-default.json
src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalDF.scala
src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsDF.scala
src/main/scala/org/globalforestwatch/summarystats/gladalerts/GladAlertsDF.scala
src/main/scala/org/globalforestwatch/summarystats/integrated_alerts/IntegratedAlertsDF.scala

The whitelist is including non-boolean values, when it should only include boolean values. 
Issue Number: GTC-2718
- Make sure whitelist only includes boolean values the demonstrate presence of layer in geometry
- Use a special version of WDPA with resampled rasters, as a workaround for the rasterization issues in the main version.

Fix types in whitelist and use WDPA version with resampled rasters
