- src/main/scala/org/globalforestwatch/summarystats/annualupdate_minimal/AnnualUpdateMinimalExport.scala
- version.sbt
For geostore and WDPA, to be on parity with GADM
Also increase number of partitions for geostore, since might get quite high.
> AnnualUpdate - filter out no change rows when exporting change table

- src/main/scala/org/globalforestwatch/features/FeatureRDDFactory.scala
- src/main/scala/org/globalforestwatch/features/FireAlertModisFeatureId.scala
- src/main/scala/org/globalforestwatch/features/FireAlertViirsFeatureId.scala
Since we cut up features to 1x1 tiles, sometimes there's an alert point exactly on the border of where we cut up the feature. When doing the GeoSpark spatial join, this creates two join records, one for each piece of the feature. We then later merge the points by feature, which causes it to get counted twice. 
Simplest solution is just to call distinct on the RDD after doing the PIP analysis to remove duplicates from the join. Already ran it on the entire VIIRS archive, and even though it causes a shuffle, it only takes like 30 seconds.
> Call distinct after PIP analysis to remove duplicates 

- src/main/scala/org/globalforestwatch/features/FeatureIdFactory.scala
- src/main/scala/org/globalforestwatch/features/FeatureRDD.scala
- src/main/scala/org/globalforestwatch/features/FeatureRDDFactory.scala
- src/main/scala/org/globalforestwatch/features/PolygonIntersectionDF.scala
- src/main/scala/org/globalforestwatch/features/WdpaFeature.scala
- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsDFFactory.scala
- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsSummary.scala
- src/main/scala/org/globalforestwatch/util/GeotrellisGeometryValidator.scala
Uses hash then range partitioning for burned areas.
- For burned areas, just use GeoSpark quadtree partitioning since it works best.
- Make sure burned areas is left dataset in spatial join, so partitioning/indexing is done on burned areas dataset.
- Fix issue where sometimes buffer geometry trick turns Polygons into MultiPolygons
- Fix bug with WDPA feature ID not being parsed correctly
- Use VIIRS grid for burned areas instead of MODIS grid
> Burned Areas Partitioning and Other Fixes

- src/main/resources/feature-flag-flagship.conf
- src/main/resources/feature-flag-pro.conf
- src/main/scala/org/globalforestwatch/config/GfwConfig.scala
- src/main/scala/org/globalforestwatch/layers/BrazilBiomes.scala
- src/main/scala/org/globalforestwatch/layers/IndonesiaForestArea.scala
- src/main/scala/org/globalforestwatch/layers/IndonesiaLandCover.scala
- src/main/scala/org/globalforestwatch/layers/IntactForestLandscapes.scala
- src/main/scala/org/globalforestwatch/layers/Layer.scala
- src/main/scala/org/globalforestwatch/layers/Plantations.scala
- src/main/scala/org/globalforestwatch/layers/ProtectedAreas.scala
- src/main/scala/org/globalforestwatch/layers/SEAsiaLandCover.scala
- src/main/scala/org/globalforestwatch/layers/TreeCoverDensity.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardCommand.scala
- src/main/scala/org/globalforestwatch/util/FeatureFlag.scala
- version.sbt
Currently the layers are hard-coded with URIs for their tiles, which is great.
A new nice-to-have is to be able to source two different versions of rasters for flagship and pro instances of this app so that data verification and integration can happen on their own independent schedules.
This PR adds the ability specify raster sources in the config files, which can be switched using the `--gfwpro` flag. 
Each source MAY use the config to get the URI template or it can continue hard-coding its URI.
This PR updates the layers required for FCD analysis because this is where the current need to maintain two versions exists.
The versions of for the PRO are pulled from "Before" state of https://github.com/wri/gfw_forest_loss_geotrellis/pull/103 …
> use conf file to source FCD layers based on feature flag

- src/main/scala/org/globalforestwatch/config/GfwConfig.scala
- src/main/scala/org/globalforestwatch/summarystats/SummaryCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardCommand.scala
- version.sbt
currently we're using `--gfwpro` flag to control which rasters get read for Pro and which tags we're using. The mechanism used however does not work on EMR because Spark does not properly serialize the state of the global variable and ends up running with default value `flagship`. Making the current mechanism work would require a pretty large refactor so the next best is the ENV variable. 
Using `GFW_FEATURE_FLAG` = `pro`, `flagship`, or null with `pro` being default behavior.
for the moment pro is the default configuration, this may not be desirable in the long-run, but either way this now needs to be considered by flagship run or changed on further discussion.
> GFW_FEATURE_FLAG

- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticDataLossYearly.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticDataValueYearly.scala
Tree cover loss values for 2020 are not present in ForestChangeDiagnostic output
2020 TCL values are included
> Fix missing 2020 in ForestChangeDiagnostic yearly summaries

- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
- version.sbt
The use use of spatial index when joining fire events point dataset to input feature list in ForestChangeDiagnostics was disable because it caused a non-obvious failure in assembling the R-Tree. Unfortunately the exact dataset is lost to time. 
However, not using the spatial index here results in unacceptable performance on the benchmark dataset: `palm_oil_mills.tsv`. The decision here is to flip the switch back on and be prepared to deal with earlier failure directly.
At the moment being able to run the benchmark dataset with expected performance is primary concern 🐬 .
This PR also incidentally uses on-disk caching for the datasets in FCD that are used more than once. These will be cleaned up when the job finishes. This should help the …
> ForestChangeDiagnostic uses spatial index

- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticExport.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardExport.scala
`coalesce(1)` sometimes hangs on large jobs,
`repartition(1)` allows shuffle to happen, fixing the apparent hangs
> Repartition instead of coalesce on export

- src/main/scala/org/globalforestwatch/features/SpatialFeatureDF.scala
- src/main/scala/org/globalforestwatch/features/ValidatedFeatureRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/ErrorSummaryRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
- src/main/scala/org/globalforestwatch/util/GeotrellisGeometryValidator.scala
- src/main/scala/org/globalforestwatch/util/IntersectGeometry.scala
- version.sbt
Current behavior is to crash upon encountering a failing geometry intersection.  Many instances of this were solved by #117, but in the event that there are other classes of geometry error that are not covered by buffering the input, crashes will still occur.
Issue Number: #118 
This PR introduces a new pathway wherein geometries are wrapped in a `Validated` structure upon import, and errors in geometry intersection can be propagated down the pipeline and reported in the output.  It's not clear if there are any other places in the code that can generate JTS errors, but there are not currently explicit catches for other (currently unknown) risky operations.
> Log intersection errors

- src/main/scala/org/globalforestwatch/summarystats/ErrorSummaryRDD.scala
- src/main/scala/org/globalforestwatch/util/PartitionSkewedRDD.scala
Using RangePartitioner on z-index of tile
Using HashPartitioner
This is a performance oriented change.
In the context the work that's being done is fetching raster tiles, each named by a z-index and performing polygonal summary for overlapping geometries. The features are grouped per tile in the partition to avoid re-fetching tiles (which is expensive)
There are two cases where partitioning here can become a problem:
1. Heavy data skew on few tiles
There are only a few tiles and they have a lot of features. Ideally the features can be spread among several partitions so the work can be done in parallel and partitions don't lag
2. Multiple partitions fetch all the same tiles
This assumes there are "few" features per tile but now we can …
> Use HashPartitioner with splitting during PolygonalSummary

- src/main/scala/org/globalforestwatch/summarystats/ErrorSummaryRDD.scala
- src/main/scala/org/globalforestwatch/util/PartitionSkewedRDD.scala
Partition by total number of features.
Partition by number of tiles needed to be downloaded.
At minimum we'll respect default parallelism to give lowest runtime on small jobs.
Otherwise cap at 16 tiles per partition which seems.
> Partition by tile count during summary

- src/main/resources/application.conf
GDAL options are set to increase raster read speed, but seem to be causing some deadlocking issues with GDAL leading to very slow read speeds on Batch.
Disable GDAL options and just use defaults.
> Disable GDAL options set for read optimization

- README.md
- src/test/resources/sample-fire-alert.tsv
Add sample fire-alert tsv file, so can run forest_change_diagnostic locally
Put example in the README of running forest_change_diagnostic locally with the sample files.
And remove mention of --limit option, which doesn't exist anymore.
> Add sample fire-alert tsv file, so can run forest_change_diagnostic locally

- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiDF.scala
Performs analysis for difference geometries and areas with null GADM values
Issue Number: [GTC-2570](https://gfw.atlassian.net/browse/GTC-2570)
- Ignores rows where `location_id = -2`
- Ignores rows where `gadm_id = "null"`
-
[GTC-2570]: https://gfw.atlassian.net/browse/GTC-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GTC-2570 Filter out rows not requiring analysis

- src/main/resources/raster-catalog-pro.json
Change to using the Oct 2023 licensed WDPA dataset for GFWPro
(rather than the public WDPA dataset).  Just changing the catalog.
Verified that the output for several input sets stayed the same with the licensed WDPA dataset.
> Change to using the licensed WDPA dataset.

- src/main/resources/raster-catalog-pro.json
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiSummary.scala
AFi Analysis currently filters out groups in which gadm_id contains any null. This causes areas without adm2 IDs, such as Singapore, to be excluded from results
Issue Number: [GTC-2598](https://gfw.atlassian.net/browse/GTC-2598)
- AFi Analysis filters out groups only when the ISO code is null
-
-
[GTC-2598]: https://gfw.atlassian.net/browse/GTC-2598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GTC-2598 Fix gadm null filter

- src/main/resources/raster-catalog-pro.json
- src/main/scala/org/globalforestwatch/layers/IntegratedAlerts.scala
- src/main/scala/org/globalforestwatch/layers/Layer.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardData.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardGrid.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardGridSources.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardRawDataGroup.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardTile.scala
Replace glad with integrated alerts in gfwpro_dashboard.
Many of these changes come from Justin's original prototype, including the switch to the 10x10m grid.
Added a new DataConfLevelsLayer that decodes three levels of confidence.  The other confidence layer DataConfLayer only decodes two levels and returns a Boolean.  So, I added a new layer, so that the existing code using DataConfLayer that expects a boolean doesn't all have to change.
In order to reduce the number of things that are changing, we are intentionally keeping the glad_* column names in the output, rather than switching to integrated_*.  We will update those in a later change, such as when we add in confidence levels in the output.
> Replace glad with integrated alerts in gfwpro_dashboard.

- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsDF.scala
For extracting alert__week from alert__date in the VIIRS analysis, we use a function that returns the iso week. The iso week can sometimes extend across years to keep week definitions consistent (e.g. December 2020 has a week 53 that extends into January 2021). 
For the corresponding alert__year value, we're using a normal year function, not the iso year function. So in the case above, January 1st 2021 will return 2021 instead of 2020. So the date will be return as week 53 of 2021, when it should be week 53 of 2020.
Issue Number: GTC-2644
Use a new extraction function that gets the iso year from the date.
> Use iso year instead of normal year for alert__year

- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardSummary.scala
Eliminate extra call to RasterExtent by reusing same value to calculate cellSize
The rasterExtent, cellSize, and pixelArea calls all show up in profiles of gfwpro_dashboard and forest_change_diagnostic. It totals up to >20% in gfwpro_dashboard for a large area, because there are not a lot of other calculations going on. Eliminating the extra call to rasterExtent inside the cellSize call eliminates at least 5%
> Eliminate extra call to RasterExtent by reusing it to calculate cellSize

- src/main/resources/raster-catalog-default.json
- src/main/resources/raster-catalog-pro.json
I noticed that there were several cases where there were multiple entries with the same dataset name in raster-catalog-pro.json and raster-catalog-default.json. Since RasterCatalog.getSourceUri() only looks for the first matching entry, the later entries are never used. So, to avoid confusion, I removed the later duplicate entries from both files.
The earlier entries (the ones being used) always have the same (or in a few cases, a later) version date, but they often have a different pixel meaning.
> Remove duplicate layer name entries in raster-catalog-*.json

- src/main/resources/raster-catalog-pro.json
- src/main/scala/org/globalforestwatch/layers/JRCForestCover.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiData.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiGrid.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiGridSources.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiTile.scala
- src/test/resources/palm-32-afi-output/part-00000-ab565f13-95b4-475b-b190-46332d027eb2-c000.csv
- src/test/resources/palm-32-afi-output/part-00000-cf173020-47f1-4ca7-8045-620c18c2a47f-c000.csv
GTC-2732 Add JRC map intersection to AFi analysis
The native JRC map is close to 10m resolution, so we move the grid and all the other datasets to 10m resolution. JRC is the more official forest cover map for EUDR vs. the SBTN natural forests map. Added two new columns in the output, jrc_forest_cover__extent and jrc_forest_cover_loss__ha, in analogy to the natural_forest_* columns.
> GTC-2732 Add JRC map intersection to AFi analysis

- build.sbt
Change  "LT-snapshots" resolver to repo.eclipse.org (from repo.locationtech.org)
This is to deal with the problem tha Geotrellis 3.7.0-SNAPSHOT was removed from one of the repos yesterday (maybe from https://repo.locationtech.org/content/groups/snapshots).
This was the solution suggested by Justin Polchlopek and seems to work fine.
> Change  "LT-snapshots" resolver to repo.eclipse.org

- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
We need all the loss years to be unique before aggregating into a map. So, we also need an extra aggregation for the gadmAgg calculation, which is combining the dissolved rows for a list id, including those with different gadms.
> Need an extra aggregation per loss year for the gadmAgg in AFi analysis

- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/test/resources/palm-32-afi-output/part-00000-a22db371-07a5-44f3-a406-818ce50afca4-c000.csv
- src/test/resources/palm-32-afi-output/part-00000-e0064552-036e-4373-ab16-ad8ef42822f8-c000.csv
Change AFi analysis to round all double results to 4 decimal places.
Because AFi analysis was written with most of the computations done in DataFrames, it never did the rounding to 4 decimal places that FCD and Dashboard do (which is built into their data types such as ForestChangeDiagnosticDataDouble and
ForestChangeDiagnosticDataLossYearly).
The rounding is useful for making sure test results match even when running in slightly different environments. Also, it makes the CSV files simpler, since GFWPro doesn't need any values to more than 4 decimal places, but AFi was giving results with up to 13 decimal places.
> Change AFi analysis to round all double results to 4 decimal places.

- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
- src/test/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysisSpec.scala
GTC-2651 (part 2) - handle "antarctica case" for gfwpro_dashboard as well
This is handling GTC-2651 for gfwpro_dashboard as well. If all locations in the input list are outside of the TCL extent (e.g. all in Antartica), then the fire analysis will fail because there is no boundary that the spatial join wants to access. So, exit out of the fireStats if the RDD is completely empty.
> GTC-2651 (part 2) - handle "antarctica case" for dashboard as well

- src/main/resources/raster-catalog-pro.json
- src/main/scala/org/globalforestwatch/config/RasterCatalog.scala
- src/main/scala/org/globalforestwatch/summarystats/SummaryMain.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticCommand.scala
- src/test/scala/org/globalforestwatch/layers/GladAlertsSuite.scala
Reduce calls to Data API for GFWPro analyses
The result of the following changes is that we now only call the data API exactly once for GFWPro dashboard analyses (previously four times), and we no longer call the data API at all for the FCD and AFi analyses.
- Remove umd_glad_landsat_alerts entry from the raster-catalog-pro.json. It is not used for GFWPro analyses (only integrated alerts is used for Dashboard), but causes a Data API call because of its use of 'latest'. I needed to adjust GladAlertsSuites, so it create GladAlerts() lazily, since that class is initialized even during GFWPro test runs.
- Removed redundant call to GfwConfig.get() in SummaryMain.scala. I'm not sure why this is here (it's been in for a while), since all the analyses have their own call to GfwConfig.get(). Maybe …
> Reduce calls to Data API for GFWPro analyses

- src/main/resources/raster-catalog-pro.json
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiData.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiGridSources.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiTile.scala
- src/test/resources/palm-32-afi-output/part-00000-6e099ea3-1c55-44d9-9d9e-4e5f3eb30723-c000.csv
- src/test/resources/palm-32-afi-output/part-00000-a02553a9-9596-42f8-b8b5-478c6b369db8-c000.csv
- src/test/resources/palm-32-afi-output/part-00000-a22db371-07a5-44f3-a406-818ce50afca4-c000.csv
- src/test/scala/org/globalforestwatch/summarystats/afi/AFiAnalysisSpec.scala
GTC-2830 Add WDPA and Landmark overlap to AFI
Adds new columns "protected_areas_area__ha" and "landmark_area__ha" with
overlap of WDPA and Landmark (single area value, no categories) for each
location and for the per-gadm dissolved list and the total dissolved
list.
I also did GTC-2832 - use May 2024 licensed WDPA in the GFWPro
Geotrellis analyses.
I also improved the AFi test slightly, by adding in an extra "dissolved list" row,
which means the GADM location code is being exercised.
> GTC-2830 Add WDPA and Landmark overlap to AFI

- src/main/scala/org/globalforestwatch/features/PointFeatureId.scala
- src/main/scala/org/globalforestwatch/features/ValidatedFeatureRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardCommand.scala
- src/test/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysisSpec.scala
GTC-2859 GPV-3183 Compute centroid for dashboard locations before 1x1 splitting
We currently compute the centroid of GFWPro locations (locId != -1) after we do 1x1 splitting. This means that if a location (locId != -1) is split into two or more pieces, then we will compute centroids for each piece of the location, and therefore may have two or more rows for the location with different GADM ids. This is not correct - we want only one row per location, with a single GADM id based on the centroid of the overall location. As far as I can tell, this bug has existed since the beginning of the
dashboard analysis.
To fix, I added an optional arg to ValidatedFeatureRDD() to specify that the centroid of locations should be computed and added to their FeatureId before any location is split up. This …
> GTC-2859 GPV-3183 Compute centroid for dashboard locations before 1x1 splitting

- src/main/scala/org/globalforestwatch/features/ValidatedFeatureRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/ErrorSummaryRDD.scala
- src/main/scala/org/globalforestwatch/summarystats/afi/AFiSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticData.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardSummary.scala
- src/main/scala/org/globalforestwatch/util/GridRDD.scala
- src/main/scala/org/globalforestwatch/util/PartitionSkewedRDD.scala
Fixed a bunch of comments in the Pro geotrellis analyses
- Fixed up some really old comments to be more accurate
- Removed comments about diff geometries in FCD, which we don't use anymore
- Added various other clarifying comments, including where combine methods are defined.
> Fixed a bunch of comments in the Pro geotrellis analyses

- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardCommand.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardDF.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardData.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardGridSources.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardRawDataGroup.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardSummary.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardTile.scala
- src/test/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysisSpec.scala
GFWPro Dashboard currently reads in the entire vector GADM file (1.9GB) in order to do a spatial join with the user input features to determine the GADM areas in the input locations and dissolved lists.
Both reading the the GADM file and doing the spatial join can take many minutes, even in the case of a small number of input features. Instead, in that case, we change to using the raster GADM layers to determine the relevant gadm locations for the locations and dissolved lists. Because we lazily read tiles for the GFWPro dashboard (see following commit), we don't read any of the GADM rasters in the case that we are using the vector GADM.
In performance runs, I have seen current batch jobs with 20-50 features that run in 6-9 minutes, but take only about 1 minutes with the same batch …
>  GTC-2824 Use raster GADM layers for pro dashboard for small # of features

- src/main/scala/org/globalforestwatch/summarystats/afi/AFiAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/forest_change_diagnostic/ForestChangeDiagnosticAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardAnalysis.scala
- src/main/scala/org/globalforestwatch/summarystats/gfwpro_dashboard/GfwProDashboardDF.scala
- src/test/scala/org/globalforestwatch/summarystats/afi/AFiAnalysisSpec.scala
In the AFi analysis, we currently don't return any row at all for a location whose geometry does not intersect the centroid of any pixel (mostly because the geometry is small compared to the pixel size). Add similar code as in FCD to detect this case and return NoIntersectionError.
Same change for GFWProDashboard as well.
I didn't make a common function for this, because the checks are slightly different between AFi, FCD, and Dashboard, and I think it's clearer to add a comment about this unusual case with the code being inline in the analysis.
Added a NoIntersection test for AFi.
> GTC-3077 Give NoIntersectionError in AFi if geometry too small

- src/main/scala/org/globalforestwatch/summarystats/firealerts/FireAlertsExport.scala
Issue Number: [GTC-2631](https://gfw.atlassian.net/browse/GTC-2631)
- Filters out VIIRS alerts more than 2 years ago
-
-
This is part of the GADM 4.1 Update. By filtering out VIIRS alerts more than two years ago, we greatly reduce the number of features for summary calculations. Flagship is accommodating that. I also found no changes needed to `annualupdate_minimal` to use GADM 4.1, although AFI and FCD analyses do hard code some GADM 3.6 information that we'll need to change later. 
[GTC-2631]: https://gfw.atlassian.net/browse/GTC-2631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GTC-2631 Filter out VIIRS alerts more than 2yrs ago

- src/main/scala/org/globalforestwatch/config/GfwConfig.scala
- src/main/scala/org/globalforestwatch/config/RasterCatalog.scala
- src/main/scala/org/globalforestwatch/layers/Layer.scala
Skip using GDAL if GFW_SKIP_GDAL env variable is set.
This is using the method that Justin used when he didn't have the right GDAL version. We avoid using GDAL by using GeoTiffRasterSource, rather than GDALRasterSource in loading tiffs in Layer.scala. This is useful for local runs where the user doesn't have the right GDAL version, but results in much slower runs (about 1.8x slower).
If we are skipping the use of GDAL, I automatically replace any 'gdal-geotiff' folder in the URI with 'geotiff', since we won't be able to deal with special GDAL-optimized tiffs. This is a fairly special case, but it's only for local use where people don't want to set up the correct GDAL version.
> Skip using GDAL if GFW_SKIP_GDAL env variable is set.
